#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
hi() { 
  clear
  echo -ne "\033[1;33m"
  cat<<-'EOF'

   .--.              .--.
   : (\ ". _......_ ." /) :
    '.    `        `    .'  
     /'   _        _   `\   Think Fast. 
    /     0}      {0     \    Learn Smart.
   |       /      \       |     Stay Wild.
   |     /'        `\     |
    \   | .  .==.  . |   /
     '._ \.' \__/ './ _.'
jgs  /  ``'._-''-_.'``  \
    /                    \

EOF
  echo -ne "\033[0m"
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

here="$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"

alias ..='cd ..'
alias ...='cd ../../../'

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias h="history"
alias ls="ls -G"

vi() {
  nvim --clean -c 'colorscheme slate' \
               -c 'set number' \
               -c 'set ts=3 sw=3 sts=3  et'  $*
}

export BASH_SILENCE_DEPRECATION_WARNING=1
export PATH="$PWD:/opt/homebrew/bin:$PATH"
export PATH="$PWD:/Library/Frameworks/Python.framework/Versions/3.13/bin:$PATH"

here() { cd $1; basename `pwd`; }
PROMPT_COMMAND='echo -ne "🐻 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
hi
